[package]
name = "eswey"
version = "0.1.0"
authors = ["wolfwood <wolfwood@xomb.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.8.1"

